### ISSUE TITLE
openMMC 2.0 roadmap

### ISSUE THREAD

**Issue by Palmitoxico** [lnls-dig/openMMC#110]
As the openMMC project has grown, it accumulated some cruft that made it difficult to port to new boards and hard to debug. I propose bellow some enhancements that I think would greatly benefit the overall user and programmer experience. This list is not set in stone and may it change according to our priorities.

Short-term (can be implemented now):
- [ ] Use OpenOCD + cmsis-dap / jlink / ftdi probes, deprecate LPCLink1 (move to a separate script) #79
- [ ] Move debug / flash logic to microcontroller specific port
- [ ] Move bootloader source to uncontroller port as it is microcontroller specific
- [ ] Firmware update integrity check
- [ ] Move from Travis CI to Github Actions
- [ ] Separate I2C mapping tables for RTM and AFC boards
- [ ] Merge all afcv3.x ports into a common code base (maybe afcv4 too?) #49 #96
- [ ] Remove AFCv3 specific code from RTM-8SFP and RTM-LAMP
- [ ] Better separate application specific code from board support code
- [ ] Consistent error passing and error checking across functions
- [ ] Better GPIO abstraction, user code shouldn't be concerned if the GPIO is behind an I/O expander or not
- [ ] Include a command line interface to ease debugging #81

Medium-term (requires careful planning):
- [ ] Avoid creating a new task for each sdr
- [ ] Check every memory allocation and do proper handling of out-of-memory and memory fragmentation situations
- [ ] Avoid macro functions, use static inline where adequate
- [ ] Replace the lpcopen hardware abstraction layer library with the CMSIS driver to avoid licensing problems (https://github.com/ARM-software/NXP_LPC/tree/master/LPC1700/CMSIS/Driver https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/Driver/Include)
- [ ] Bufferred interrupt based UART to avoid blocking #108
- [ ] Proper I2C master driver (interrupt based, block tasks using semaphores not loops, transparent I2C mux configuration)
- [ ] Use a thread-safe printf implementation #90
- [ ] Run bootloader from RAM to allow self update

Long-term (low priority, requires more complex changes):
- [ ] Better use of Continuous Integration #97
- [ ] Enable MPU for cortex-m3/4 microcontrollers, use the FreeRTOS MPU port
